import * as constant from './constant';

export const style_firm = {
  firm_search_box: {
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  firm_search: {
    backgroundColor: '#fff',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 19,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: constant.primary_color,
    shadowOffset: {height: 0, width: 0},
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  firm_avatar_bar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 8,
    paddingHorizontal: 8,
    paddingVertical: 16,
  },
  firm_subscription: {
    color: constant.primary_color,
    borderStyle: 'solid',
    borderColor: constant.primary_color,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  firm_statistic: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 16,
  },
  firm_logos_box: {
    backgroundColor: '#fafafa',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingVertical: 4,
    paddingHorizontal: 24,
  },
  firm_logos_item: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 16,
  },
  firm_detail_exchanges: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    paddingVertical: 16,
    marginHorizontal: 8,
  },
  firm_detail_assets_title: {
    marginHorizontal: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  firm_detail_assets_total_bar: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginHorizontal: 8,
    paddingVertical: 24,
  },
  firm_detail_assets_bar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 24,
  },
  firm_detail_assets_tabs: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginHorizontal: 8,
    paddingVertical: 12,
    position: 'relative',
  },
  firm_detail_assets_tabs_title: {
    fontSize: 18,
    fontWeight: 'bold',
    position: 'absolute',
    left: 8,
  },
  firm_detail_position_percent: {
    marginHorizontal: 8,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  firm_detail_position_percent_text: {
    textAlign: 'center',
    color: constant.text_white,
    fontWeight: 'bold',
  },
  firm_detail_position_percent_label: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 16,
  },
  firm_detail_position_label_box: {
    flexDirection: 'row',
    width: '50%',
    marginTop: 8,
  },
  firm_detail_position_tabel_title_box: {
    marginHorizontal: 8,
    paddingVertical: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  firm_detail_position_tabel_title_text: {
    color: constant.text_gray,
    textAlign: 'center',
  },
  firm_detail_position_tabel_column_center: {
    color: constant.text_gray,
    fontSize: 18,
    textAlign: 'center',
  },
  firm_detail_position_tabel_column_end: {
    color: constant.text_green,
    fontSize: 18,
    marginTop: 4,
  },
  firm_detail_ops_timeline_tail: {
    position: 'absolute',
    left: 10.5,
    top: 10.5,
    height: '120%',
    borderStyle: 'solid',
    borderColor: '#c8c8c8',
    borderLeftWidth: 1,
  },
  firm_detail_ops_timeline_head: {
    zIndex: 999,
    backgroundColor: '#fff',
  },
  firm_detail_ops_timeline_left: {
    color: constant.text_gray,
    textAlign: 'right',
  },
  firm_detail_ops_timeline_right: {
    paddingVertical: 4,
    borderRadius: 11,
    width: 48,
  },
  firm_detail_activity_title: {
    marginHorizontal: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  firm_detail_activity_none: {
    marginHorizontal: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 24,
  },
  firm_detail_activity_item: {
    marginHorizontal: 8,
    padding: 16,
    flexDirection: 'row',
  },
  firm_detail_activity_ipt_box: {
    position: 'relative',
    bottom: 0,
    borderStyle: 'solid',
    borderColor: '#e6e6e6',
    borderTopWidth: 1,
    paddingHorizontal: 24,
    paddingVertical: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    backgroundColor: constant.text_white,
  },
  firm_detail_activity_ipt: {
    backgroundColor: '#f5f5f5',
    width: '75%',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 15,
  },
  firm_detail_activity_btn: {
    backgroundColor: constant.primary_color,
    width: '20%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 15,
  },
};
