import * as CONST from './constant'

export const style_firm = {
  firm_search_box: {
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  firm_search: {
    backgroundColor: CONST.N0,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: CONST.PRIMARY,
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    height: 40,
    borderRadius: 20,
  },
  firm_search_ipt: {
    marginLeft: 8,
    width: '100%',
  },
  firm_avatar_bar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 8,
    paddingHorizontal: 8,
    paddingVertical: 16,
  },
  firm_subscription: {
    height: 24,
    paddingHorizontal: 8,
    justifyContent: 'center',
    borderRadius: 12,
    borderStyle: 'solid',
    borderWidth: 1,
  },
  firm_subscription_PRIMARY: {
    color: CONST.PRIMARY,
    borderColor: CONST.PRIMARY,
  },
  firm_subscription_gray: {
    color: CONST.N200,
    borderColor: CONST.N200,
  },
  firm_statistic: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 16,
  },
  firm_logos_box: {
    backgroundColor: '#fafafa',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingVertical: 4,
    paddingHorizontal: 24,
  },
  firm_logos_item: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 16,
  },
  firm_detail_exs: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    paddingVertical: 16,
    marginHorizontal: 8,
  },
  firm_detail_assets_title: {
    marginHorizontal: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  firm_detail_assets_total_bar: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginHorizontal: 8,
    paddingVertical: 24,
  },
  firm_detail_assets_bar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 24,
  },
  firm_detail_assets_tabs: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginHorizontal: 8,
    paddingVertical: 12,
    position: 'relative',
  },
  firm_detail_assets_tabs_title: {
    fontSize: 18,
    fontWeight: 'bold',
    position: 'absolute',
    left: 16,
  },
  firm_detail_position_percent: {
    marginHorizontal: 8,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  firm_detail_position_percent_text: {
    textAlign: 'center',
    color: CONST.N0,
    fontWeight: 'bold',
  },
  firm_detail_position_percent_label: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 16,
  },
  firm_detail_position_label_box: {
    flexDirection: 'row',
    width: '50%',
    marginTop: 8,
  },
  firm_detail_position_tabel_title_box: {
    marginHorizontal: 8,
    paddingVertical: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  firm_detail_position_tabel_title_text: {
    color: CONST.N96,
    textAlign: 'center',
  },
  firm_detail_position_tabel_col_center: {
    color: CONST.N96,
    fontSize: 18,
    textAlign: 'center',
  },
  firm_detail_position_tabel_col_end: {
    color: CONST.GREEN,
  },
  firm_detail_ops_tl_tail: {
    position: 'absolute',
    left: 10.5,
    top: 10.5,
    height: '120%',
    borderStyle: 'solid',
    borderColor: CONST.N200,
    borderLeftWidth: 1,
  },
  firm_detail_ops_tl_head: {
    zIndex: 999,
    backgroundColor: CONST.N0,
  },
  firm_detail_ops_tl_left: {
    color: CONST.N96,
    textAlign: 'right',
  },
  firm_detail_ops_tl_right: {
    paddingVertical: 4,
    borderRadius: 11,
    width: 48,
  },
  firm_detail_act_title: {
    marginHorizontal: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  firm_detail_act_none: {
    marginHorizontal: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 24,
  },
  firm_detail_act_item: {
    marginHorizontal: 8,
    padding: 16,
    flexDirection: 'row',
  },
  firm_detail_act_ipt_box: {
    position: 'relative',
    bottom: 0,
    borderStyle: 'solid',
    borderColor: '#e6e6e6',
    borderTopWidth: 1,
    paddingHorizontal: 24,
    paddingVertical: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    backgroundColor: CONST.N0,
  },
  firm_detail_act_ipt: {
    backgroundColor: '#f5f5f5',
    width: '75%',
    paddingHorizontal: 16,
    height: 40,
    borderRadius: 20,
  },
  firm_detail_act_btn: {
    backgroundColor: CONST.PRIMARY,
    width: '20%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 15,
  },
  firm_contract_list_label_box: {
    position: 'absolute',
    borderTopRightRadius: 6,
    borderBottomRightRadius: 6,
    top: 0,
    left: 0,
  },
  firm_contract_list_label: {
    color: CONST.N0,
    fontSize: 10,
    paddingHorizontal: 8,
  },
  firm_contract_detail_list_title: {
    marginHorizontal: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  firm_contract_detail_list_label: {
    color: CONST.PRIMARY,
    borderStyle: 'solid',
    borderColor: CONST.PRIMARY,
    borderWidth: 1,
    fontSize: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  firm_contract_detail_list_line: {
    marginHorizontal: 8,
    paddingHorizontal: 16,
    paddingBottom: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  firm_empty_box: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
}
