import * as CONST from './constant'

export const style_mine = {
  mine_linearGradient: {
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
  },
  mine_card_box: {
    padding: 24,
    flexDirection: 'row',
  },
  mine_card_left: {
    marginLeft: 16,
    justifyContent: 'space-between',
  },
  mine_userinfo_btn: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    width: 80,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mine_grid_box: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: 24,
  },
  mine_grid_divider: {
    height: '90%',
    borderStyle: 'solid',
    borderColor: CONST.N238,
    borderLeftWidth: 1,
  },
  mine_grid_desc: {
    color: CONST.N0,
    fontSize: 16,
    marginTop: 10,
  },
  mine_list_box: {
    padding: 16,
    paddingBottom: 8,
  },
  mine_list_lin_box: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  mine_list_line: {
    paddingHorizontal: 8,
    paddingVertical: 16,
    borderStyle: 'solid',
    borderColor: CONST.N238,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  mine_list_line_text: {
    fontSize: 16,
    marginLeft: 16,
  },
  mine_nickname: {
    color: CONST.N0,
    fontSize: 18,
  },
  mine_bar: {
    flexGrow: 1,
    alignItems: 'center',
  },
  mine_bar_item: {
    color: CONST.N0,
    fontSize: 20,
  },
  sub_list_box: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: 16,
    padding: 16,
    borderStyle: 'solid',
    borderColor: CONST.N238,
    borderBottomWidth: 1,
  },
  wallet_icon_box: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    padding: 8,
  },
  wallet_amount: {
    color: CONST.GOLD,
    fontSize: 28,
  },
  wallet_unit: {
    color: CONST.GOLD,
    fontSize: 16,
    marginLeft: 8,
  },
  wallet_divider: {
    borderStyle: 'solid',
    borderColor: CONST.GOLD,
    borderWidth: 1,
    marginHorizontal: 10,
  },
  wallet_amount: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'baseline',
  },
  wallet_btn_box: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    padding: 8,
    marginTop: 24,
  },
  wallet_btn: {
    width: 90,
    padding: 5,
    alignItems: 'center',
    borderRadius: 3,
    borderStyle: 'solid',
    borderColor: CONST.GOLD,
    borderWidth: 1,
    marginRight: 8,
  },
  wallet_btn_GOLD: {
    backgroundColor: CONST.GOLD,
    width: 90,
    padding: 5,
    alignItems: 'center',
    borderRadius: 3,
  },
  recharge_box: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    flexWrap: 'wrap',
    padding: 16,
    paddingTop: 0,
  },
  recharge_item_box: {
    borderStyle: 'solid',
    borderColor: CONST.N200,
    borderWidth: 1,
    alignItems: 'center',
    padding: 16,
    marginTop: 16,
    width: '30%',
    borderRadius: 5,
  },
  recharge_divider: {
    borderStyle: 'solid',
    borderColor: CONST.N238,
    borderBottomWidth: 1,
    width: '90%',
    alignSelf: 'center',
  },
  recharge_amount_input: {
    borderStyle: 'solid',
    borderColor: CONST.N238,
    borderWidth: 1,
    padding: 8,
    marginVertical: 16,
    textAlign: 'right',
    borderRadius: 5,
  },
  recharge_amount_tip: {
    alignSelf: 'flex-end',
    color: CONST.N96,
  },
  recharge_sticky_btn: {
    backgroundColor: CONST.PRIMARY,
    width: '80%',
    alignSelf: 'center',
    padding: 16,
    borderRadius: 23,
    marginBottom: 50,
  },
  firm_access_tag_box: {
    backgroundColor: 'rgba(255, 94, 0, 0.1)',
    marginLeft: 10,
    borderRadius: 10,
  },
  firm_access_tag_text: {
    color: CONST.PRIMARY,
    fontSize: 12,
    paddingVertical: 3,
    paddingHorizontal: 8,
  },
  api_access_input: {
    borderStyle: 'solid',
    borderColor: CONST.N238,
    borderWidth: 1,
    padding: 8,
    marginBottom: 24,
    borderRadius: 5,
  },
  api_access_sticky_btn: {
    backgroundColor: CONST.PRIMARY,
    width: '80%',
    alignSelf: 'center',
    padding: 16,
    borderRadius: 23,
    marginBottom: 50,
  },
  firm_set_item_box: {
    borderStyle: 'solid',
    borderColor: CONST.N238,
    borderBottomWidth: 1,
    paddingHorizontal: 16,
    marginBottom: 24,
  },
  firm_set_radio_box: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 16,
  },
  account_avatar_box: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
  },
  account_item_box: {
    borderStyle: 'solid',
    borderColor: CONST.N238,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
  },
  nickname_sticky_btn: {
    backgroundColor: CONST.PRIMARY,
    width: '80%',
    alignSelf: 'center',
    justifyContent: 'center',
    height: 50,
    borderRadius: 25,
    marginBottom: 50,
  },
  intro_length: {
    position: 'absolute',
    right: 10,
    bottom: 35,
    color: CONST.N96,
  },
  service_card: {
    backgroundColor: CONST.N0,
    height: '60%',
    width: '80%',
    marginTop: 80,
    marginBottom: 100,
    shadowColor: CONST.N238,
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 10,
  },
  service_text: {
    fontSize: 16,
    color: CONST.N96,
    marginBottom: 8,
  },
  service_wechat_box: {
    alignItems: 'center',
    justifyContent: 'center',
    height: '25%',
  },
  service_wechat_btn: {
    backgroundColor: CONST.PRIMARY,
    width: 150,
    padding: 8,
    borderRadius: 23,
    marginTop: 16,
  },
  service_wechat_btn_text: {
    textAlign: 'center',
    color: CONST.N0,
    fontSize: 16,
  },
}
