import * as constant from './constant';

export const style_mine = {
  mine_linearGradient: {
    width: '100%',
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
  },
  mine_avatar: {
    height: 60,
    width: 60,
    borderRadius: 30,
  },
  mine_userinfo_btn: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    width: 90,
    padding: 4,
    borderRadius: 12,
    marginTop: 5,
    alignItems: 'center',
  },
  mine_grid_box: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: 24,
  },
  mine_grid_divider: {
    height: '90%',
    borderStyle: 'solid',
    borderColor: '#eee',
    borderLeftWidth: 1,
  },
  mine_grid_desc: {
    color: constant.text_white,
    fontSize: 16,
    marginTop: 10,
  },
  mine_list_line: {
    paddingHorizontal: 8,
    paddingVertical: 16,
    borderStyle: 'solid',
    borderColor: '#eee',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sub_list_box: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: 16,
    padding: 16,
    borderStyle: 'solid',
    borderColor: '#eee',
    borderBottomWidth: 1,
  },
  sub_list_avatar: {
    height: 40,
    width: 40,
    borderRadius: 20,
  },
  wallet_divider: {
    borderStyle: 'solid',
    borderColor: constant.gold,
    borderWidth: 1,
    marginHorizontal: 10,
  },
  wallet_amount: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'baseline',
  },
  wallet_btn_box: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    padding: 8,
    marginTop: 24,
  },
  wallet_btn: {
    width: 90,
    padding: 5,
    alignItems: 'center',
    borderRadius: 3,
    borderStyle: 'solid',
    borderColor: constant.gold,
    borderWidth: 1,
    marginRight: 8,
  },
  wallet_btn_gold: {
    backgroundColor: constant.gold,
    width: 90,
    padding: 5,
    alignItems: 'center',
    borderRadius: 3,
  },
  recharge_item_box: {
    borderStyle: 'solid',
    borderColor: '#c8c8c8',
    borderWidth: 1,
    alignItems: 'center',
    padding: 16,
    width: '30%',
    borderRadius: 5,
  },
  recharge_divider: {
    borderStyle: 'solid',
    borderColor: '#eee',
    borderBottomWidth: 1,
    width: '90%',
    alignSelf: 'center',
  },
  recharge_amount_input: {
    borderStyle: 'solid',
    borderColor: '#eee',
    borderWidth: 1,
    padding: 8,
    marginVertical: 16,
    textAlign: 'right',
    borderRadius: 5,
  },
  recharge_amount_tip: {
    alignSelf: 'flex-end',
    color: constant.text_gray,
  },
  recharge_sticky_btn: {
    backgroundColor: constant.primary_color,
    width: '80%',
    alignSelf: 'center',
    padding: 16,
    borderRadius: 23,
    marginBottom: 50,
  },
  firm_access_tag_box: {
    backgroundColor: 'rgba(255, 94, 0, 0.1)',
    marginLeft: 10,
    borderRadius: 10,
  },
  firm_access_tag_text: {
    color: '#ff5e00',
    fontSize: 12,
    paddingVertical: 3,
    paddingHorizontal: 8,
  },
  api_access_input: {
    borderStyle: 'solid',
    borderColor: '#eee',
    borderWidth: 1,
    padding: 8,
    marginBottom: 24,
    borderRadius: 5,
  },
  api_access_sticky_btn: {
    backgroundColor: constant.primary_color,
    width: '80%',
    alignSelf: 'center',
    padding: 16,
    borderRadius: 23,
    marginBottom: 50,
  },
  firm_set_item_box: {
    borderStyle: 'solid',
    borderColor: '#eee',
    borderBottomWidth: 1,
    paddingHorizontal: 16,
  },
  firm_set_radio_box: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 16,
  },
  account_avatar_box: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
  },
  account_item_box: {
    borderStyle: 'solid',
    borderColor: constant.border_gray,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
  },
  nickname_sticky_btn: {
    backgroundColor: constant.primary_color,
    width: '80%',
    alignSelf: 'center',
    padding: 16,
    borderRadius: 23,
    marginBottom: 50,
  },
  intro_length: {
    position: 'absolute',
    right: 10,
    bottom: 35,
    color: constant.text_gray,
  },
  service_card: {
    backgroundColor: '#fff',
    height: '60%',
    width: '80%',
    marginTop: 80,
    marginBottom: 100,
    shadowColor: '#eee',
    shadowOffset: {height: 0, width: 0},
    shadowOpacity: 1,
    shadowRadius: 10,
  },
  service_text: {
    fontSize: 16,
    color: constant.text_gray,
    marginBottom: 8,
  },
  service_wechat_box: {
    alignItems: 'center',
    justifyContent: 'center',
    height: '25%',
  },
  service_wechat_btn: {
    backgroundColor: constant.primary_color,
    width: 150,
    padding: 8,
    borderRadius: 23,
    marginTop: 16,
  },
  service_wechat_btn_text: {
    textAlign: 'center',
    color: constant.text_white,
    fontSize: 16,
  },
};
